name             'test-cookbook'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures test-cookbook'
long_description 'Installs/Configures test-cookbook'
version          '0.1.0'


depends 'nginx'
depends 'hostsfile'
depends 'mysql'
depends 'mysql2_chef_gem'
depends 'database'
depends 'php'
depends 'phpmyadmin'
